services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=redis://redis:6379/0
      - ACCESS_TTL_SEC=60
      - REFRESH_TTL_SEC=604800
      - FRONTEND_ORIGINS=http://localhost:3000,http://127.0.0.1:3000
      - COOKIE_SECURE=false
    env_file:
      - .env
    volumes:
      - ../data/e823e08eb26ea8cdb30f4174bebcebc7.jpg:/app/data/cat.jpg:ro
    depends_on:
      - redis

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: /api
    ports:
      - "3000:80"
    depends_on:
      - backend
